version: '{build}'
image: Visual Studio 2017
platform:
  - x86
  - x64
configuration:
  - Debug
  - Release
build:
  parallel: true
  project: MfcToolkit.sln
  verbosity: minimal
artifacts:
  - path: collections\bin\$(configuration)\$(platform)
    name: MFC.Collections-$(platform)-$(configuration)-build$(appveyor_build_version)
  - path: controls\bin\$(configuration)\$(platform)
    name: MFC.Controls-$(platform)-$(configuration)-build$(appveyor_build_version)
  - path: language\bin\$(configuration)\$(platform)
    name: MFC.Language-$(platform)-$(configuration)-build$(appveyor_build_version)
  - path: lua\bin\$(configuration)\$(platform)
    name: Lua-$(platform)-$(configuration)-build$(appveyor_build_version)
  - path: tinyxml2\bin\$(configuration)\$(platform)
    name: TinyXml2-$(platform)-$(configuration)-build$(appveyor_build_version)
  - path: utilities\bin\$(configuration)\$(platform)
    name: MFC.Utilities-$(platform)-$(configuration)-build$(appveyor_build_version)
